### ISSUE TITLE
Perfect, Timeline on the PWA

### ISSUE THREAD

**Issue by noobskies** [Huniko519/ChatGPT-React-Next-Web#2]
I can help if needed, I just want to know how/when you are going to achieve the PWA part

**Comment by devcrafta** [comment]
Hi @noobskies.
Nice to meet you.
I don't understand your message.
Could you explain to me correctly?
Thanks...

**Comment by noobskies** [comment]
you mention "Mobile app (PWA)" I was wanting to know when this would be possible, I would love to use this for android and IOS if possible

**Comment by devcrafta** [comment]
The Mobile App PWA portion is not yet developed.
I am currently very busy with other work, so I do not have time to develop at the moment.
I can invite you to my project and You can update source code.

**Comment by devcrafta** [comment]
> you mention "Mobile app (PWA)" I was wanting to know when this would be possible, I would love to use this for android and IOS if possible

You can use this project to your Android and IOS development.
